In [2]:
import torch
import numpy as np

# Indexing, Slicing 

In [4]:
x= torch.rand(size=(3,4))
x

tensor([[0.6232, 0.7157, 0.4793, 0.5311],
        [0.3298, 0.5751, 0.8214, 0.7975],
        [0.3616, 0.1452, 0.6852, 0.2587]])

x[row, col]

row -> start:stop:step

col -> start:stop:step

In [8]:
x[0,:]

tensor([0.6232, 0.7157, 0.4793, 0.5311])

In [9]:
x[:,0]

tensor([0.6232, 0.3298, 0.3616])

In [10]:
x[0:2, 0:3]

tensor([[0.6232, 0.7157, 0.4793],
        [0.3298, 0.5751, 0.8214]])

In [11]:
x[0:2, 0:3:2]

tensor([[0.6232, 0.4793],
        [0.3298, 0.8214]])

In [15]:
x[0,0] + 11

tensor(11.6232)

In [16]:
x[0,0]

tensor(0.6232)

In [17]:
x = torch.rand(size=(3,4))
y= torch.rand(size=(3,4))

## Concatenation

In [18]:
torch.cat((x,y), dim=0)

tensor([[0.5871, 0.0726, 0.5634, 0.4524],
        [0.6146, 0.3328, 0.6508, 0.3215],
        [0.4353, 0.4752, 0.3531, 0.2023],
        [0.0753, 0.5408, 0.7042, 0.0461],
        [0.0838, 0.2074, 0.2575, 0.3130],
        [0.6356, 0.8841, 0.8065, 0.2591]])

In [19]:
torch.cat((x,y), dim=1)

tensor([[0.5871, 0.0726, 0.5634, 0.4524, 0.0753, 0.5408, 0.7042, 0.0461],
        [0.6146, 0.3328, 0.6508, 0.3215, 0.0838, 0.2074, 0.2575, 0.3130],
        [0.4353, 0.4752, 0.3531, 0.2023, 0.6356, 0.8841, 0.8065, 0.2591]])

## Reshaping

In [20]:
x

tensor([[0.5871, 0.0726, 0.5634, 0.4524],
        [0.6146, 0.3328, 0.6508, 0.3215],
        [0.4353, 0.4752, 0.3531, 0.2023]])

In [21]:
x.shape

torch.Size([3, 4])

In [23]:
x.reshape(2,6)

tensor([[0.5871, 0.0726, 0.5634, 0.4524, 0.6146, 0.3328],
        [0.6508, 0.3215, 0.4353, 0.4752, 0.3531, 0.2023]])

In [25]:
x.reshape(2,4)  # number of elements should match

RuntimeError: shape '[2, 4]' is invalid for input of size 12

In [26]:
x.reshape(1,12)

tensor([[0.5871, 0.0726, 0.5634, 0.4524, 0.6146, 0.3328, 0.6508, 0.3215, 0.4353,
         0.4752, 0.3531, 0.2023]])

In [27]:
x.reshape(12,1)

tensor([[0.5871],
        [0.0726],
        [0.5634],
        [0.4524],
        [0.6146],
        [0.3328],
        [0.6508],
        [0.3215],
        [0.4353],
        [0.4752],
        [0.3531],
        [0.2023]])

In [28]:
x

tensor([[0.5871, 0.0726, 0.5634, 0.4524],
        [0.6146, 0.3328, 0.6508, 0.3215],
        [0.4353, 0.4752, 0.3531, 0.2023]])

In [33]:
x.shape

torch.Size([3, 4])

In [32]:
# Flatening 
x.view(-1)

tensor([0.5871, 0.0726, 0.5634, 0.4524, 0.6146, 0.3328, 0.6508, 0.3215, 0.4353,
        0.4752, 0.3531, 0.2023])

In [34]:
x.view(-1).shape # flattening a tensor

torch.Size([12])

In [38]:
# batch falttening  ops
batch= 16
torch.rand((batch, 2,5)).view((batch,-1))

tensor([[0.6671, 0.1461, 0.4456, 0.1117, 0.8637, 0.2523, 0.8669, 0.4059, 0.5099,
         0.1737],
        [0.3297, 0.9520, 0.2989, 0.1645, 0.9270, 0.8445, 0.1380, 0.0177, 0.8309,
         0.3720],
        [0.6398, 0.4571, 0.2822, 0.9596, 0.9266, 0.0565, 0.1670, 0.1426, 0.7326,
         0.2713],
        [0.8439, 0.1151, 0.1750, 0.2448, 0.7857, 0.1535, 0.1558, 0.2594, 0.7661,
         0.2719],
        [0.2761, 0.5677, 0.3171, 0.0735, 0.7185, 0.9571, 0.7896, 0.1748, 0.0187,
         0.8639],
        [0.9918, 0.8273, 0.9624, 0.9286, 0.3543, 0.9159, 0.3272, 0.7747, 0.2971,
         0.2054],
        [0.9533, 0.8606, 0.5678, 0.5930, 0.8537, 0.4492, 0.5367, 0.2711, 0.3891,
         0.1705],
        [0.2467, 0.9715, 0.4166, 0.6319, 0.0795, 0.4363, 0.7695, 0.3343, 0.7140,
         0.9782],
        [0.4674, 0.3465, 0.8992, 0.7211, 0.6643, 0.6126, 0.9259, 0.5891, 0.1416,
         0.1738],
        [0.4044, 0.9273, 0.2240, 0.9920, 0.8317, 0.3439, 0.8628, 0.6912, 0.3373,
         0.1212],
        [0

In [39]:
torch.rand((batch, 2,5)).shape

torch.Size([16, 2, 5])

In [40]:
torch.rand((batch, 2,5)).view((batch,-1)).shape

torch.Size([16, 10])