# 

In [1]:
import numpy as np
import torch
import os

In [5]:
x = torch.arange(start=10, end=20, step=4)
y= torch.arange(start=5, end=15, step=4)
x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [6]:
x

tensor([10, 14, 18])

In [7]:
y

tensor([ 5,  9, 13])

In [4]:
x+y

tensor([15, 23, 31])

In [8]:
x-y

tensor([5, 5, 5])

In [9]:
x*y #<< element wise multiplication

tensor([ 50, 126, 234])

In [27]:
torch.dot(x,y)

tensor(410)

In [10]:
x/y  #<< element wise division

tensor([2.0000, 1.5556, 1.3846])

In [12]:
z= torch.ones(3)
z

tensor([1., 1., 1.])

In [14]:
z= z+x
z

tensor([21., 29., 37.])

In [15]:
# inplace addition 
z.add_(x)

tensor([31., 43., 55.])

In [16]:
x.pow(2)

tensor([100, 196, 324])

In [17]:
x**2

tensor([100, 196, 324])

In [18]:
x >0

tensor([True, True, True])

In [21]:
# Matrix Multiplication
A = torch.rand(size=(3,5))
B= torch.rand(size=(5,4))

In [22]:
A @ B

tensor([[1.3896, 2.2202, 2.1122, 0.7249],
        [1.0981, 1.5520, 1.2161, 0.7590],
        [0.4104, 1.0674, 0.9884, 0.5505]])

In [23]:
A.matmul(B)

tensor([[1.3896, 2.2202, 2.1122, 0.7249],
        [1.0981, 1.5520, 1.2161, 0.7590],
        [0.4104, 1.0674, 0.9884, 0.5505]])

In [24]:
X= torch.rand(size= (3,3))
X.matrix_exp()

tensor([[1.4428, 0.6731, 0.5526],
        [0.3178, 1.6540, 0.9900],
        [0.5409, 1.3382, 2.2459]])

In [26]:
X.matrix_power(2)

tensor([[0.1982, 0.3707, 0.4171],
        [0.2294, 0.5463, 0.5110],
        [0.3420, 0.7278, 0.8460]])

In [30]:
# Broadcasting

A 

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [31]:
A + 1

tensor([[1.3980, 1.2148, 1.7507, 1.9010, 1.4744],
        [1.3100, 1.9869, 1.0309, 1.2555, 1.5633],
        [1.0884, 1.3481, 1.6584, 1.0705, 1.1281]])

In [32]:
A - 1

tensor([[-0.6020, -0.7852, -0.2493, -0.0990, -0.5256],
        [-0.6900, -0.0131, -0.9691, -0.7445, -0.4367],
        [-0.9116, -0.6519, -0.3416, -0.9295, -0.8719]])

In [33]:
A * 5

tensor([[1.9902, 1.0741, 3.7534, 4.5048, 2.3719],
        [1.5498, 4.9347, 0.1547, 1.2773, 2.8165],
        [0.4419, 1.7403, 3.2918, 0.3527, 0.6406]])

In [34]:
A.shape

torch.Size([3, 5])

In [35]:
C = torch.ones(size= (1,5))
C

tensor([[1., 1., 1., 1., 1.]])

In [38]:
A

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [36]:
A - C

tensor([[-0.6020, -0.7852, -0.2493, -0.0990, -0.5256],
        [-0.6900, -0.0131, -0.9691, -0.7445, -0.4367],
        [-0.9116, -0.6519, -0.3416, -0.9295, -0.8719]])

In [37]:
A + C

tensor([[1.3980, 1.2148, 1.7507, 1.9010, 1.4744],
        [1.3100, 1.9869, 1.0309, 1.2555, 1.5633],
        [1.0884, 1.3481, 1.6584, 1.0705, 1.1281]])

In [39]:
D = torch.ones(size= (3,1))
D

tensor([[1.],
        [1.],
        [1.]])

In [40]:
A

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [41]:
A - D

tensor([[-0.6020, -0.7852, -0.2493, -0.0990, -0.5256],
        [-0.6900, -0.0131, -0.9691, -0.7445, -0.4367],
        [-0.9116, -0.6519, -0.3416, -0.9295, -0.8719]])

In [43]:
A + D

tensor([[1.3980, 1.2148, 1.7507, 1.9010, 1.4744],
        [1.3100, 1.9869, 1.0309, 1.2555, 1.5633],
        [1.0884, 1.3481, 1.6584, 1.0705, 1.1281]])

In [45]:
D

tensor([[1.],
        [1.],
        [1.]])

In [46]:
torch.sum(D)

tensor(3.)

In [47]:
torch.sum(A)

tensor(6.1789)

In [48]:
 A

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [49]:
torch.max(A)

tensor(0.9869)

In [50]:
torch.min(A)

tensor(0.0309)

In [51]:
torch.min(A, dim=1)

torch.return_types.min(
values=tensor([0.2148, 0.0309, 0.0705]),
indices=tensor([1, 2, 3]))

In [54]:
torch.max(A, dim=1) # Row  wise max value


torch.return_types.max(
values=tensor([0.9010, 0.9869, 0.6584]),
indices=tensor([3, 1, 2]))

In [55]:
torch.max(A, dim=0)  # Col wise max value

torch.return_types.max(
values=tensor([0.3980, 0.9869, 0.7507, 0.9010, 0.5633]),
indices=tensor([0, 1, 0, 0, 1]))

In [56]:
torch.abs(-A)

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [60]:
A

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [59]:
torch.argmax(A)

tensor(6)

In [61]:
torch.argmin(A)

tensor(7)

In [62]:
torch.mean(A, dim=0) # col wise mean

tensor([0.2655, 0.5166, 0.4800, 0.4090, 0.3886])

In [63]:
torch.mean(A, dim=1) # row wise mean

tensor([0.5478, 0.4293, 0.2587])

In [64]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [65]:
torch.eq(A, D)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [66]:
torch.eq(D, D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [67]:
A

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.0309, 0.2555, 0.5633],
        [0.0884, 0.3481, 0.6584, 0.0705, 0.1281]])

In [68]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.2148, 0.3980, 0.4744, 0.7507, 0.9010],
        [0.0309, 0.2555, 0.3100, 0.5633, 0.9869],
        [0.0705, 0.0884, 0.1281, 0.3481, 0.6584]]),
indices=tensor([[1, 0, 4, 2, 3],
        [2, 3, 0, 4, 1],
        [3, 0, 4, 1, 2]]))

In [69]:
torch.clamp(A, min=0.2)

tensor([[0.3980, 0.2148, 0.7507, 0.9010, 0.4744],
        [0.3100, 0.9869, 0.2000, 0.2555, 0.5633],
        [0.2000, 0.3481, 0.6584, 0.2000, 0.2000]])