In [1]:
import torch
import numpy as np
import os

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
basic_tensor= torch.tensor([[1,2,3], [4,5,6]])
basic_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
basic_tensor.dtype

torch.int64

In [7]:
basic_tensor.device

device(type='cpu')

In [8]:
basic_tensor.shape

torch.Size([2, 3])

In [9]:
basic_tensor.requires_grad

False

In [11]:
tensor= torch.tensor([[1,2,3], [4,5,6]],
                    dtype= torch.float,                    
                     device= device,
                    requires_grad= True)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [12]:
tensor.dtype

torch.float32

In [13]:
tensor.device

device(type='cuda', index=0)

In [14]:
tensor.requires_grad

True

In [15]:
tensor.shape

torch.Size([2, 3])

## Other Commonly used Tensors

In [17]:
x= torch.empty(size= (3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
x= torch.zeros(size= (3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
x= torch.ones(size= (3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
x= torch.rand(size= (3,3))
x

tensor([[0.8536, 0.9711, 0.8596],
        [0.7581, 0.4524, 0.2991],
        [0.1588, 0.5210, 0.9610]])

In [30]:
x= torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
x= torch.arange(start=0, end=7, step=2)
x

tensor([0, 2, 4, 6])

In [47]:
x= torch.linspace(start=0, end=7, steps=10)
x

tensor([0.0000, 0.7778, 1.5556, 2.3333, 3.1111, 3.8889, 4.6667, 5.4444, 6.2222,
        7.0000])

In [48]:
x= torch.rand(size= (3,3)).normal_(mean=0, std=1)
x

tensor([[-0.5886,  1.4673,  0.7120],
        [-1.5521,  0.6311,  0.4207],
        [-0.6552, -0.0863, -1.1340]])

In [50]:
x= torch.rand(size= (3,3)).uniform_()
x

tensor([[0.8430, 0.9490, 0.4861],
        [0.9292, 0.6256, 0.1979],
        [0.8486, 0.3445, 0.1387]])

In [51]:
x= torch.rand(size= (3,3)).uniform_(3,6)
x

tensor([[3.3972, 3.8513, 4.6014],
        [3.6970, 3.8004, 4.9063],
        [3.2535, 3.4198, 4.6839]])

In [53]:
x= torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
x.shape

torch.Size([10, 10])

In [55]:
x= torch.diag(5*torch.ones(10))
x

tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

## Conversions

In [56]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [57]:
x.bool()

tensor([False,  True,  True,  True])

In [58]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [60]:
x.short() # int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [61]:
x.long() #int64

tensor([0, 1, 2, 3])

In [62]:
x.half() #float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [63]:
x.float()

tensor([0., 1., 2., 3.])

In [64]:
x.dtype

torch.int64

In [67]:
x.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [68]:
np_array= np.array([[1,2,3],[1,2,3]])
np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [70]:
tensor= torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)

In [71]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])